__author__ = 'Insality'

# Game consts
GAME_NAME = "Pyrox"

# Directions
RIGHT = 0
UP = 1
LEFT = 2
DOWN = 3
DIRECTIONS = [RIGHT, UP, LEFT, DOWN]

# Map consts
TILE_SIZE = 24
TILE_ANCHOR = (0, TILE_SIZE)

# Window consts
# TILES_IN_ROW = 45
# TILES_IN_COL = 30

TILES_IN_ROW = 18
TILES_IN_COL = 10
WINDOW_WIDTH = TILES_IN_ROW * TILE_SIZE
WINDOW_HEIGHT = TILES_IN_COL * TILE_SIZE

# Generator consts
ROOM_MIN_WIDTH = 6
ROOM_MIN_HEIGHT = 6
ROOM_MAX_WIDTH = 10
ROOM_MAX_HEIGHT = 10

GEN_MAX_TRY_PLACE_ROOM = 4

HALL_MIN_LENGTH = 2
HALL_MAX_LENGTH = 5

# Generator symbols
TILE_EMPTY = ' '
TILE_SOLID = '#'
TILE_FLOOR = '.'
TILE_WALL = '+'
TILE_DOOR = 'D'